### ISSUE TITLE
Error of type in duration variable on parseRoad

### ISSUE THREAD

**Issue by renehw** [liodali/OSM-Routing-Client-Dart#1]
Hi, I found an error in your package, when I pass the coordinates for the `getRoad()` an error is throw on line 41 and 43 of utils.dart, the duration variable get a value double but the type is int and throws the error `type 'double' is not a subtype of type 'int' in type cast
`.

![exemplo 1](https://user-images.githubusercontent.com/58603535/145832768-6586cde7-6e81-406b-aa2b-04425cead8c4.png)

![exemplo 2](https://user-images.githubusercontent.com/58603535/145832791-e44eb94a-5a43-4051-b02d-9142b28dc72d.png)

`[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [versÃ£o 10.0.19042.1348], locale pt-BR)`
`[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)`

**Comment by liodali** [comment]
check the new version `0.1.1`

**Comment by renehw** [comment]
Your update solved the problem, thank you!

**Comment by renehw** [comment]
Hi @liodali , I am implemanting trip service but I have a problem with type of variable.

```
E/flutter ( 5881): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: type 'int' is not a subtype of type 'double' in type cast
E/flutter ( 5881): #0      new Road.fromOSRMJson
package:routing_client_dart/…/models/road.dart:43
E/flutter ( 5881): #1      parseTrip
package:routing_client_dart/…/utilities/utils.dart:88
E/flutter ( 5881): #2      _IsolateConfiguration.apply
package:flutter/…/foundation/_isolates_io.dart:83
E/flutter ( 5881): #3      _spawn.<anonymous closure>
package:flutter/…/foundation/_isolates_io.dart:90
E/flutter ( 5881): #4      _spawn.<anonymous closure>
package:flutter/…/foundation/_isolates_io.dart:89
E/flutter ( 5881): #5      Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter ( 5881): #6      _spawn
package:flutter/…/foundation/_isolates_io.dart:87
E/flutter ( 5881): #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
E/flutter ( 5881): #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter ( 5881):
```

![image](https://user-images.githubusercontent.com/58603535/153433202-529585f4-a091-43bb-9fed-91cf1f6906f9.png)


Att.

**Comment by liodali** [comment]
ok i will fix that

**Comment by liodali** [comment]
check `0.3.0+1`

**Comment by renehw** [comment]
Your update solved the problem, thank you!

**Comment by renehw** [comment]
But, how use the road response with drawRoadManually? Because drawRoadManually need a `List<GeoPoint>` and the getTrip don't return this.

**Comment by renehw** [comment]
Thanks man, I will test!

**Comment by renehw** [comment]
Maybe the type of the list that getTrip should receive is not correct, because as the type of the list is LngLat, and GeoPoint's is LatLng, it ends up shuffling the data, changing the order drawnRoadManualy should receive.

But that's my opinion of what might be returning the error.

![image](https://user-images.githubusercontent.com/58603535/153637453-38e40f87-29ed-4467-9398-3d9d19fe3b3e.png)
