### ISSUE TITLE
Missing Instructions! ->  route.CopyWith() is NOT assigning instructions. v1.0.4

### ISSUE THREAD

**Issue by Ger4W** [liodali/OSM-Routing-Client-Dart#26]
Hi @liodali,

OSM-Routing client is a great package! Thanks!

While trying it out we noticed that getOSRMRoad() works and returns a useful response, but it does not contain the instructions so, after inspecting and debbuging further, we noticed that the route.CopyWith() is not assigning the instructions correctly.

Is there a specific way to query the service? Or to configure the request so that it returns the instructions along with the routing data?

Thank you so much!

Regards

**Comment by liodali** [comment]
you're using the latest version ? `1.0.4` or `0.5.5`
because if you're `0.5.5` you neee to build instructions but in the latest version we fixed that and we add it new service valhalla route

**Comment by liodali** [comment]
you're using the latest version ? `1.0.4` or `0.5.5`
because if you're `0.5.5` you neee to build instructions but in the latest version we fixed that and we add it new service valhalla route
ah you already using latest one 
i will check the issue it should work as expected

**Comment by liodali** [comment]
new version will be available in minutes `1.0.5`

**Comment by Ger4W** [comment]
Working great!

Thanks
